[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

# Redirect default Netlify subdomain to primary domain
http://havesomeleeway.netlify.com/* http://havesomeleeway.com/:splat 301!